# Render Configuration
services:
  - type: web
    name: hitreport
    env: node
    buildCommand: yarn install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production